/*
 * This source file was generated by the Gradle 'init' task
 */
package com.skax.academicadmin;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // 테스트 코드 예시
}
